use_frameworks!

target 'MyPodLib_Example' do
  pod 'MyPodLib', :path => '../'

  target 'MyPodLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
